# Generated by Django 4.1.1 on 2022-11-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_projectorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='message3',
        ),
    ]
