# Generated by Django 4.1.1 on 2022-11-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_message_message_message3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message3',
            field=models.CharField(max_length=30000, null=True),
        ),
    ]
