# Generated by Django 4.1.1 on 2022-11-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_message_message3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(max_length=100)),
                ('Project_description', models.CharField(max_length=500)),
                ('Project_explanations', models.CharField(max_length=30000)),
                ('image', models.ImageField(upload_to='home/')),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message3',
            new_name='message',
        ),
    ]
